Document: wallpaper-eumetsat
Title: Debian wallpaper-eumetsat Manual
Author: <insert document author here>
Abstract: This manual describes what wallpaper-eumetsat is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/wallpaper-eumetsat/wallpaper-eumetsat.sgml.gz

Format: postscript
Files: /usr/share/doc/wallpaper-eumetsat/wallpaper-eumetsat.ps.gz

Format: text
Files: /usr/share/doc/wallpaper-eumetsat/wallpaper-eumetsat.text.gz

Format: HTML
Index: /usr/share/doc/wallpaper-eumetsat/html/index.html
Files: /usr/share/doc/wallpaper-eumetsat/html/*.html
